Use version Python 3.11.3

In [ ]:
#DEFAULT
from pickle import dump
# 3RD PARTY
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from catboost import CatBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from lightgbm import LGBMClassifier, log_evaluation, early_stopping
from sklearn.model_selection import GridSearchCV
import pandas as pd
#CUSTOM

c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ml\.venv-ml\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# # Create train and test sets
# train_size = 0.8
# test_size = 0.2

# dataset_labels_file = '../../data/training/training_dataset_labels_wo_manual_review.csv'
# dataset_labels = pd.read_csv(dataset_labels_file).dropna(subset=['best_tool'])

# number_of_classes = dict()
# for label_class in dataset_labels['best_tool'].unique():
#     number_of_classes[label_class] = len(dataset_labels[dataset_labels['best_tool'] == label_class])
# print("Number of classes:", number_of_classes)
# majority_class = max(number_of_classes, key=number_of_classes.get)
# majority_class_count = number_of_classes[majority_class]
# minority_class = min(number_of_classes, key=number_of_classes.get)
# minority_class_count = number_of_classes[minority_class]
# if majority_class_count != minority_class_count:
#     print(f"Class imbalance detected! The majority class will be downsampled to the size of the minority class.")
#     diff_count = majority_class_count - minority_class_count
#     print(diff_count)
#     dataset_labels_major = dataset_labels[dataset_labels['best_tool'] == majority_class].sample(n=diff_count, random_state=420)
#     print(dataset_labels_major)
#     dataset_labels = dataset_labels.drop(dataset_labels_major.index)
#     print(f"Downsampling successful! New class distrbution: {dataset_labels['best_tool'].value_counts()}")
# else:
#     print("No class imbalance detected. Proceed...")

# label_encoder = LabelEncoder()
# dataset_labels['best_tool_encoded'] = label_encoder.fit_transform(dataset_labels['best_tool'])
# label_mapping = {index: label for index, label in enumerate(label_encoder.classes_)}
# print("Label Mapping:", label_mapping)

# train_df, test_df = train_test_split(dataset_labels, test_size=test_size, random_state=420, stratify=dataset_labels['best_tool_encoded'])

Number of classes: {'vouchervision': 962, 'herbonauten': 437}
Class imbalance detected! The majority class will be downsampled to the size of the minority class.
525
     catalogNumber      best_tool
592     B101012139  vouchervision
740     B101027775  vouchervision
1380    B101213754  vouchervision
1226    B101181517  vouchervision
1215    B101181071  vouchervision
...            ...            ...
1328    B101196700  vouchervision
537     B100766268  vouchervision
734     B101027634  vouchervision
1286    B101184475  vouchervision
647     B101019818  vouchervision

[525 rows x 2 columns]
Downsampling successful! New class distrbution: best_tool
herbonauten      437
vouchervision    437
Name: count, dtype: int64
Label Mapping: {0: 'herbonauten', 1: 'vouchervision'}

In [ ]:
# # Prepare the feature data for training and evaluation

# train_size = 0.8
# test_size = 0.2

# labels = pd.read_csv('../../data/training/training_dataset_labels_wo_manual_review.csv')
# labels = labels.dropna(subset=['best_tool'])
# label_encoder = LabelEncoder()
# labels['best_tool_encoded'] = label_encoder.fit_transform(labels['best_tool'])
# label_mapping = {index: label for index, label in enumerate(label_encoder.classes_)}
# print("Label Mapping:", label_mapping)

# train_df, test_df = train_test_split(labels, test_size=test_size, random_state=42, stratify=labels['best_tool_encoded'])

# df_handcrafted = pd.read_csv('../../data/features/extracted_handcrafted_features.csv', index_col=0)
# df_handcrafted['catalogNumber'] = df_handcrafted.index.str.split("/").str[-1].str.split(".").str[0]
# df_label_features = pd.read_csv('../../data/features/label_features_normalized.csv', index_col=0)
# df_label_features['catalogNumber'] = df_label_features.index.str.split("/").str[-1].str.split(".").str[0]
# df_features = df_handcrafted.merge(df_label_features, on='catalogNumber', how='inner')

# label_encoder = LabelEncoder()
# label_encoder.fit(labels['best_tool'])

# df_features_labels = df_features.merge(labels[['catalogNumber', 'best_tool']], on='catalogNumber', how='inner')
# df_features_labels['best_tool_encoded'] = label_encoder.transform(df_features_labels['best_tool'])
# df_features_labels = df_features_labels.drop(columns=['best_tool'])
# df_features_labels = df_features_labels.set_index('catalogNumber')
# x_train_handcrafted = df_features_labels.loc[train_df['catalogNumber']].drop(columns=['best_tool_encoded'])
# y_train_handcrafted = df_features_labels.loc[train_df['catalogNumber'], 'best_tool_encoded']
# x_test_handcrafted = df_features_labels.loc[test_df['catalogNumber']].drop(columns=['best_tool_encoded'])
# y_test_handcrafted = df_features_labels.loc[test_df['catalogNumber'], 'best_tool_encoded']
# x_train_handcrafted

Label Mapping: {0: 'herbonauten', 1: 'vouchervision'}

,mean_conf,min_conf,std_conf,words_count,char_count,num_text_lines,num_text_blocks,low_conf_ratio,text_density,handwriting_ocr,...,noise_sigma,background_uniformity,overlapped_label_area,detected_lang_encoded,number_of_labels,mean_label_width,mean_label_height,label_spread,areas,handwritten_flag
catalogNumber,,,,,,,,,,,,,,,,,,,,,
B101096568,0.780467,0.000000,0.568743,0.124706,0.121378,0.344828,0.44,0.188679,0.138939,0.0,...,2.554237e-01,0.249884,0.002851,0.230769,0.333333,0.547137,0.328937,0.0,0.195730,0.0
B101178574,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.546756,0.0,...,2.086779e-01,0.379263,0.000000,1.000000,0.333333,0.543612,0.324815,0.0,0.192032,0.0
B101071317,0.694576,0.056966,0.612934,0.072941,0.050819,0.258621,0.20,0.290323,0.000000,0.0,...,3.706101e-01,0.469855,0.000000,0.230769,0.000000,0.000000,0.000000,0.0,0.000000,0.0
B100671735,0.644154,0.000000,0.644415,0.075294,0.073919,0.155172,0.28,0.375000,0.855658,0.0,...,1.032526e-30,0.228662,0.000000,1.000000,0.333333,0.355947,0.219291,0.0,0.084890,0.0
B101127778,0.867698,0.003239,0.552936,0.157647,0.166317,0.327586,0.52,0.179104,0.165038,0.0,...,2.212034e-01,0.218309,0.000000,0.230769,0.333333,0.696916,0.407255,0.0,0.308671,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B100158719,0.667266,0.000000,0.691629,0.101176,0.087358,0.206897,0.36,0.348837,0.376316,0.0,...,1.032526e-30,0.103877,0.000000,0.461538,0.333333,0.520705,0.318219,0.0,0.180205,0.0
B101011525,0.635601,0.000000,0.729775,0.072941,0.069299,0.189655,0.28,0.387097,0.225950,0.0,...,4.515761e-01,0.442623,0.000000,0.230769,0.000000,0.000000,0.000000,0.0,0.000000,0.0
B101135155,0.660370,0.064350,0.679720,0.068235,0.045779,0.224138,0.16,0.413793,0.090876,0.0,...,1.310680e-01,0.124728,0.000788,0.192308,0.333333,0.615859,0.274526,0.0,0.183871,0.0
B101182532,0.659570,0.000000,0.720977,0.169412,0.145737,0.344828,0.48,0.402778,0.231920,0.0,...,1.869831e-01,0.204757,0.000000,0.230769,0.333333,0.549780,0.523495,0.0,0.313005,0.0
B101122989,0.722470,0.000000,0.647449,0.122353,0.129777,0.275862,0.28,0.250000,0.206144,0.0,...,1.527628e-01,0.262612,0.064329,0.230769,0.333333,0.604405,0.516900,0.0,0.339769,0.0

In [ ]:
# # save the train and test sets as well as the label mapping to CSV or TXT files 
# train_df.to_csv('../../data/training/train_set.csv', index=False)
# test_df.to_csv('../../data/training/test_set.csv', index=False)

# with open('../../data/training/label_mapping.txt', 'w') as f:
#     for label, num in label_mapping.items():
#         f.write(f"{label}\t{num}\n")

In [ ]:
# Training dataset preparation
train_df = pd.read_csv('../../data/training/train_set.csv')
test_df = pd.read_csv('../../data/training/test_set.csv')

df_handcrafted = pd.read_csv('../../data/features/extracted_handcrafted_features.csv', index_col=0)
df_handcrafted['catalogNumber'] = df_handcrafted.index.str.split("/").str[-1].str.split(".").str[0]
df_label_features = pd.read_csv('../../data/features/label_features_normalized.csv', index_col=0)
df_label_features['catalogNumber'] = df_label_features.index.str.split("/").str[-1].str.split(".").str[0]
df_features = df_handcrafted.merge(df_label_features, on='catalogNumber', how='inner')
label_encoder = LabelEncoder()
labels = pd.read_csv('../../data/training/training_dataset_labels.csv')
labels = labels.dropna(subset=['best_tool'])
label_encoder.fit(labels['best_tool'])
label_mapping = {index: label for index, label in enumerate(label_encoder.classes_)}
training_dataset_without_manual_review = pd.read_csv('../../data/training/training_dataset_labels_wo_manual_review.csv')
# training_dataset_without_manual_review = pd.read_csv('../../data/training/training_dataset_labels.csv')

df_features_labels = df_features.merge(labels[['catalogNumber', 'best_tool']], on='catalogNumber', how='inner')
df_features_labels['best_tool_encoded'] = label_encoder.transform(df_features_labels['best_tool'])
df_features_labels = df_features_labels.drop(columns=['best_tool'])
df_features_labels = df_features_labels.set_index('catalogNumber')
x_train_handcrafted = df_features_labels.loc[train_df['catalogNumber']].drop(columns=['best_tool_encoded'])
y_train_handcrafted = df_features_labels.loc[train_df['catalogNumber'], 'best_tool_encoded']
# store trainig set
df_features_labels.loc[train_df['catalogNumber']].to_csv('../../data/training/train_set_features.csv')
# store test set
df_features_labels.loc[test_df['catalogNumber']].to_csv('../../data/training/test_set_features.csv')
x_test_handcrafted = df_features_labels.loc[test_df['catalogNumber']].drop(columns=['best_tool_encoded'])
y_test_handcrafted = df_features_labels.loc[test_df['catalogNumber'], 'best_tool_encoded']
y_train_handcrafted

best_features = x_train_handcrafted.columns
x_train = x_train_handcrafted
y_train = y_train_handcrafted
x_test = x_test_handcrafted
y_test = y_test_handcrafted

In [ ]:
best_features # TODO: Rename

Index(['mean_conf', 'min_conf', 'std_conf', 'words_count', 'char_count',
       'num_text_lines', 'num_text_blocks', 'low_conf_ratio', 'text_density',
       'handwriting_ocr', 'detected_lang_conf', 'text_area',
       'mean_orientation', 'relative_label_centroid_x',
       'relative_label_centroid_y', 'resolution', 'laplacian', 'contrast',
       'brightness', 'noise', 'noise_sigma', 'background_uniformity',
       'overlapped_label_area', 'detected_lang_encoded', 'number_of_labels',
       'mean_label_width', 'mean_label_height', 'label_spread', 'areas',
       'handwritten_flag'],
      dtype='object')

In [ ]:
# Function for  evaluating trained models
def run_model(model, x_test, y_test):
    preds = model.predict(x_test[list(best_features)])
    errors = preds != y_test
    accuracy = np.mean(preds == y_test)
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Number of errors: {errors.sum()} out of {len(y_test)} ({errors.sum() / len(y_test) * 100:.2f}%)")
    cm = confusion_matrix(y_test, preds)
    cr = classification_report(y_test, preds)
    print("Model Evaluation:")
    print(cm)
    print(cr)
    return accuracy, cm, cr

In [ ]:
# Hyperparameter optimization with GridSearchCV 
# Uncommented parts show the ranges of hyperparameters evaluated
param_grids = {
    'RandomForest': {
        'n_estimators': [140],
        # 'n_estimators': [int(x) for x in np.linspace(start=55, stop=175, num=8)],
        'max_features': ['sqrt'],
        #'max_features': ['log2', 'sqrt'],
        'max_depth': [None],
        # 'max_depth': [None] + [int(x) for x in np.linspace(10, 100, num=6)],
        'min_samples_split': [10],
        # 'min_samples_split': [5, 10, 20],
        'min_samples_leaf': [1],
        # 'min_samples_leaf': [1, 2, 4],
        'bootstrap': [True],
        # 'bootstrap': [True, False],
        'criterion': ['gini']
        # 'criterion': ['gini', 'entropy']
    },
    'SVC': {
        'C': [100],
        # 'C': [1e-6, 1e-4, 1e-3, 0.01, 0.1, 1, 10, 100],
        'gamma': [0.1],
        # 'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1],
        'kernel': ['rbf'],
        # 'kernel': ['rbf', 'linear']
        'max_iter': [-1]
        # 'max_iter': [-1, 1, 10, 100, 1000]
    },
    'MLPClassifier': { # Max-Gain: 0.04	
        'hidden_layer_sizes': [42],
        # 'hidden_layer_sizes': [int(x) for x in np.linspace(start=1, stop=50, num=49)],
        'activation': ['relu'],
        # 'activation': ['logistic', 'relu', 'tanh', 'identity'],
        'learning_rate_init': [0.000999],
        # 'learning_rate_init': [0.0001, 0.0005, 0.000999, 0.001, 0.005, 0.01, 0.1],
        'solver': ['adam'],
        # 'solver': ['adam', 'sgd'],
        'batch_size': [16],
        # 'batch_size': [int(x) for x in np.linspace(start=16, stop=128, num=8)],
        # 'early_stopping': [True],
        'alpha': [0.0001875],
        # 'alpha': [float(x) for x in np.linspace(start=0.00010, stop=0.00020, num=9)]
    },
    'KNN': { # Max-Gain: 0.034286
        'n_neighbors': [24],
        # 'n_neighbors': [int(x) for x in np.linspace(start=2, stop=50, num=49)],
        'weights': ['distance'],
        # 'weights': ['uniform', 'distance'],
        'metric': ['manhattan'],
        # 'metric': ['minkowski', 'euclidean', 'manhattan', 'cityblock', 'cosine', 'haversine', 'l1', 'l2', 'nan_euclidean'],
    },
    'LogReg': { # Max-Gain 0.0
        'C': [1.0],
        # 'C': [0.1, 1.0, 10.0],
        'solver': ['liblinear'],
        # 'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
        'l1_ratio': [0],
        # 'l1_ratio': [0, 1],
    },
    'NB': { # Max-Gain: 0.005714
        # 'var_smoothing': [0.002],
        'var_smoothing': [2e-1, 2e-2, 2e-3, 2e-4, 2e-5, 2e-6, 2e-7]
    },  
    'LightGBM': { # Max-Gain: 0.062857
        'num_leaves': [8],
        # 'num_leaves': [2, 4, 8, 16, 24, 32],
        'n_estimators': [26],
        # 'n_estimators': [int(x) for x in np.linspace(start=2, stop=32, num=31)],
        'max_depth': [-1],
        # 'max_depth': [-1, 0, 2, 4, 6, 8, 10, 15, 20],
        'min_child_samples': [20],
        # 'min_child_samples': [5, 10, 20, 30, 40, 50],
        'learning_rate': [0.09721804511278195], 
        # 'learning_rate': [float(x) for x in np.linspace(start=0.098, stop=0.02, num=400)],
        'reg_alpha': [0.00725],
        # 'reg_alpha': [float(x) for x in np.linspace(start=0.006, stop=0.011, num=5)]
    },
    'GradientBoosting': { # Max-Gain: 0.011429
        'n_estimators': [14],
        # 'n_estimators': [int(x) for x in np.linspace(start=2, stop=100, num=99)],
        'loss': ['log_loss'],
        # 'loss': ['log_loss', 'exponential'],
        'learning_rate': [0.1],
        # 'learning_rate': [float(x) for x in np.linspace(start=0.09, stop=0.11, num=21)],
        'min_samples_split': [20],
        # 'min_samples_split': [2, 5, 10, 20, 30],
        'min_samples_leaf': [19],
        # 'min_samples_leaf': [int(x) for x in np.linspace(start=15, stop=20, num=6)],
        'max_depth': [3],
        # 'max_depth': [None, 3, 5, 10],
        'max_features': ['log2'],
        # 'max_features': ['sqrt', 'log2'], # log2
        'subsample': [0.681] # num=80
        # 'subsample': [float(x) for x in np.linspace(start=0.1, stop=1.0, num=80)] # num=80
    }
}

# Test single model from the param_grids to check if the function works TODO: Remove later
# param_grids = {'RandomForest': param_grids['RandomForest']}
param_grids = {'SVC': param_grids['SVC']}
# param_grids = {'MLPClassifier': param_grids['MLPClassifier']}
# param_grids = {'KNN': param_grids['KNN']}
# param_grids = {'LogReg': param_grids['LogReg']}
# param_grids = {'NB': param_grids['NB']}
# param_grids = {'LightGBM': param_grids['LightGBM']}
# param_grids = {'GradientBoosting': param_grids['GradientBoosting']}

def run_all_models(x_train, y_train, x_test, y_test, param_grids):
    best_models = {}
    callbacks = []
    for model_name, param_grid in param_grids.items():
        print(f"Running GridSearchCV for {model_name}...")
        # Initialize each model
        if model_name == 'RandomForest':
            model = RandomForestClassifier(random_state=42)
        elif model_name == 'SVC':
            model = SVC(random_state=42, probability=True)
        elif model_name == 'MLPClassifier':
            model = MLPClassifier(random_state=42)
        elif model_name == 'CatBoostClassifier':
            model = CatBoostClassifier(random_state=42, verbose=0)
        elif model_name == 'KNN':
            model = KNeighborsClassifier()
        elif model_name == 'LogReg':
            model = LogisticRegression(random_state=42)
        elif model_name == 'NB':
            model = GaussianNB()
        elif model_name == 'LightGBM':
            model = LGBMClassifier(random_state=42)
            callbacks.append(log_evaluation(period=0))
            callbacks.append(early_stopping(stopping_rounds=10))
        elif model_name == 'AdaBoost':
            model = AdaBoostClassifier(random_state=42)
        elif model_name == 'GradientBoosting':
            model = GradientBoostingClassifier(random_state=42)
        grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
        if model_name == 'LightGBM':
            grid_search.fit(x_train[list(best_features)], y_train, callbacks=callbacks, eval_set=[(x_test[list(best_features)], y_test)], eval_metric='binary_logloss')
        else:
            grid_search.fit(x_train[list(best_features)], y_train)
        # print all accuracies for all parameter combinations
        print("All Hyperparameter combinations and their corresponding mean test scores:")
        for mean_score, params in zip(grid_search.cv_results_['mean_test_score'], grid_search.cv_results_['params']):
            print(f"{mean_score:.4f} for {params}")

        print(f"Best Hyperparameters for {model_name}:", grid_search.best_params_)
        best_model = grid_search.best_estimator_
        # best_preds = best_model.predict(x_test[list(best_features)])
        # best_cm = confusion_matrix(y_test, best_preds)
        # best_cr = classification_report(y_test, best_preds)
        # print(best_cm)
        # print(best_cr)
        best_models[model_name] = best_model
        dump(best_model, open(f'../../models/tabular/best_{model_name}_grid.pkl', 'wb')) # save the best model
        results_df = pd.DataFrame(grid_search.cv_results_)
        results_df.to_csv(f'../../models/{model_name}_grid_search_results.csv', index=False) # save cross-validation results
    return best_models
best_models = run_all_models(x_train, y_train, x_test, y_test, param_grids)

# comparison of the trained models with default settings of them
results = []
for model_name, best_model in best_models.items():
    print(f"Evaluating {model_name}...")
    accuracy, cm, cr = run_model(best_model, x_test, y_test)
    default_model = None
    if model_name == 'RandomForest':
        default_model = RandomForestClassifier(random_state=42)
    elif model_name == 'SVC':
        default_model = SVC(random_state=42)
    elif model_name == 'MLPClassifier':
        default_model = MLPClassifier(random_state=42)
    elif model_name == 'CatBoostClassifier':
        default_model = CatBoostClassifier(random_state=42, verbose=0)
    elif model_name == 'KNN':
        default_model = KNeighborsClassifier()
    elif model_name == 'LogReg':
        default_model = LogisticRegression(random_state=42)
    elif model_name == 'NB':
        default_model = GaussianNB()
    elif model_name == 'LightGBM':
        default_model = LGBMClassifier(random_state=42)
    elif model_name == 'AdaBoost':
        default_model = AdaBoostClassifier(random_state=42)
    default_model.fit(x_train[list(best_features)], y_train)
    default_accuracy, default_cm, default_cr = run_model(default_model, x_test, y_test)

    results.append({
        'model': model_name,
        'accuracy': accuracy,
        'accuracy_gain': accuracy - default_accuracy,
        'confusion_matrix': cm,
        'classification_report': cr
    })

results_df = pd.DataFrame(results)
# results_df.to_csv('../../models/model_comparison_results.csv', index=False)
results_df

Running GridSearchCV for SVC...
Fitting 3 folds for each of 1 candidates, totalling 3 fits
All Hyperparameter combinations and their corresponding mean test scores:
0.7282 for {'C': 100, 'gamma': 0.1, 'kernel': 'rbf', 'max_iter': -1}
Best Hyperparameters for SVC: {'C': 100, 'gamma': 0.1, 'kernel': 'rbf', 'max_iter': -1}
Evaluating SVC...
Accuracy: 0.7771
Number of errors: 39 out of 175 (22.29%)
Model Evaluation:
[[66 22]
 [17 70]]
              precision    recall  f1-score   support

           0       0.80      0.75      0.77        88
           1       0.76      0.80      0.78        87

    accuracy                           0.78       175
   macro avg       0.78      0.78      0.78       175
weighted avg       0.78      0.78      0.78       175

Accuracy: 0.7543
Number of errors: 43 out of 175 (24.57%)
Model Evaluation:
[[68 20]
 [23 64]]
              precision    recall  f1-score   support

           0       0.75      0.77      0.76        88
           1       0.76      0.74      0.75        87

    accuracy                           0.75       175
   macro avg       0.75      0.75      0.75       175
weighted avg       0.75      0.75      0.75       175

,model,accuracy,accuracy_gain,confusion_matrix,classification_report
0,SVC,0.777143,0.022857,"[[66, 22], [17, 70]]",precision recall f1-score ...