Python 3.9

In [ ]:
#DEFAULT
from subprocess import Popen, PIPE
import os
import gzip
import csv
import time
import os
import json
#3RD PARTY
import cv2
import pytesseract
import pandas as pd
import numpy as np
from skimage.restoration import estimate_sigma
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from ultralytics import YOLO
import langdetect
import urllib
#CUSTOM

In [ ]:
class FeatureExtractor:
    def __init__(self):
        self.features = dict()
        self.normalized_features = dict()
        # Min max values to normalize features based on the dataset already learned by the tabular model
        self.min_max_values = json.load(open("../../data/training/normalization_min_max_values.json", "r"))

    def extract_ocr_based_features(self, image_path):
        img = cv2.imread(image_path)
        ocr_data = pytesseract.image_to_data(img, output_type=pytesseract.Output.DATAFRAME)
        ocr_data = ocr_data[ocr_data.conf != -1] if not ocr_data.empty else ocr_data # remove empty rows
        ocr_data = ocr_data[ocr_data.text.str.strip() != ''] if not ocr_data.empty else ocr_data 
        if ocr_data.empty:
            return dict(
                mean_conf=0.0,
                min_conf=0.0,
                std_conf=0.0,
                words_count=0,
                char_count=0,
                num_text_lines=0,
                num_text_blocks=0,
                low_conf_ratio=0.0,
                text_density=0.0,
                handwriting_ocr=0.0,
                detected_lang='zz',
                detected_lang_conf=0.0
            )
        mean_conf = ocr_data.conf.mean()
        min_conf = ocr_data.conf.min()
        std_conf = ocr_data.conf.std()
        words_count = len(ocr_data)
        char_count = ocr_data['text'].str.len().sum()
        num_text_lines = sum([max(line_numbers) for _, line_numbers in ocr_data.groupby('block_num')['line_num']])
        num_text_blocks = ocr_data['block_num'].nunique()
        low_conf_ratio = (ocr_data.conf < 50).sum() / words_count # ratio of words with very bad confidence below 50
        text_density = (ocr_data.width * ocr_data.height).sum() / img.shape[0] * img.shape[1] # ratio of text area to image area
        handwriting_ocr = 1.0 if mean_conf < 50 and text_density > 0.05 else 0.0
        detected_lang, detected_lang_conf = self._get_languages_from_ocr(ocr_data)
        return dict(
            mean_conf=mean_conf,
            min_conf=min_conf,
            std_conf=std_conf,
            words_count=words_count,
            char_count=char_count,
            num_text_lines=num_text_lines,
            num_text_blocks=num_text_blocks,
            low_conf_ratio=low_conf_ratio,
            text_density=text_density,
            handwriting_ocr=handwriting_ocr,
            detected_lang=detected_lang,
            detected_lang_conf=detected_lang_conf
        )
        
    def extract_visual_features(self, image_path):
        img = cv2.imread(image_path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (17, 3))
        dilated = cv2.dilate(thresh, kernel, iterations=1)
        contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        total_image_area = img.shape[0] * img.shape[1]
        relevant_countours = 0
        text_area = 0
        label_coordinates = []
        mean_orientation = 0
        x_min, y_min = img.shape[1], img.shape[0]
        x_max, y_max = 0, 0

        # heuristic size measurements
        for cnt in contours:
            x, y, w, h = cv2.boundingRect(cnt)
            area = w * h
            if area < 400:
                continue
            if area > 0.075 * total_image_area:
                continue
            if w / float(h) < 1.2:
                continue
            cy = y + h / 2.0
            if cy < img.shape[0] * 2 / 3:
                continue
            if w > 20 and h > 10: 
                relevant_countours += 1
                text_area += w * h
                label_coordinates.append((x, y, w, h))
                mean_orientation += np.arctan2(h, w)
                x_min = x if x < x_min else x_min
                x_max = x + w if x + w > x_max else x_max
                y_min = y if y < y_min else y_min
                y_max = y + h if y + h > y_max else y_max

        text_density = text_area / total_image_area
        mean_orientation = mean_orientation / max(relevant_countours, 1)
        relative_label_centroid_x = (x_min + x_max) / 2.0 / img.shape[1]
        relative_label_centroid_y = (y_min + y_max) / 2.0 / img.shape[0]

        return dict(
            text_density=text_density,
            text_area=text_area,
            mean_orientation=mean_orientation,
            relative_label_centroid_x=relative_label_centroid_x,
            relative_label_centroid_y=relative_label_centroid_y
        )
    
    def extract_label_features(self, images_folder_path):
        label_features_dict = dict()
        labels_dict = self._identify_labels_using_yolo(images_folder_path)
        labels_dict = dict(list(labels_dict.items()))
        for image, boxes in labels_dict.items():
            number_of_labels = len(boxes)
            label_coordinates = boxes
            mean_label_width = 0.0
            mean_label_height = 0.0
            areas = 0.0
            centroids_x = []
            centroids_y = []
            for box in boxes:
                x1, y1, x2, y2 = box
                width = x2 - x1
                height = y2 - y1
                mean_label_width += width
                mean_label_height += height
                areas += width * height
                centroids_x.append(x1 + x2 / 2.0)
                centroids_y.append(y1 + y2 / 2.0)
            if number_of_labels > 0:
                mean_label_width = mean_label_width / number_of_labels
                mean_label_height = mean_label_height / number_of_labels
            else:
                mean_label_width = 0.0
                mean_label_height = 0.0
            spread_centroids_x = np.std(centroids_x) if len(centroids_x) > 1 else 0.0
            spread_centroids_y = np.std(centroids_y) if len(centroids_y) > 1 else 0.0
            label_spread = np.sqrt(spread_centroids_x ** 2 + spread_centroids_y ** 2)
            handwritten_flag = 0.0 # TODO: Use a classifier to determine if handwritten or not
            label_features_dict[image.split("\\")[-1]] = {
                'number_of_labels': number_of_labels,
                'label_coordinates': label_coordinates,
                'mean_label_width': mean_label_width,
                'mean_label_height': mean_label_height,
                'label_spread': label_spread,
                'areas': areas,
                'handwritten_flag': handwritten_flag
            }
            
        return label_features_dict
    
    def extract_image_quality_features(self, input_image_path, label_features=None):
        input_image = cv2.imread(input_image_path)
        gray = cv2.cvtColor(input_image, cv2.COLOR_BGR2GRAY)
        resolution = input_image.shape[1] * input_image.shape[0] / 1000000  # in megapixels
        laplacian = cv2.Laplacian(gray, cv2.CV_64F).var()
        contrast = gray.std()
        brightness = gray.mean()
        noise = cv2.fastNlMeansDenoising(gray, None, 10, 7, 21) # quite slow
        noise = np.mean((gray - noise) ** 2)
        noise_sigma = np.mean(estimate_sigma(gray, average_sigmas=True))
        background_uniformity = self._calculate_background_heterogeneity(gray)
        overlapped_label_area = self._check_for_overlaps(input_image_path, label_features)
        image_quality_features = dict(
            resolution=resolution,
            laplacian=laplacian,
            contrast=contrast,
            brightness=brightness,
            noise=noise,
            noise_sigma=noise_sigma,
            background_uniformity=background_uniformity,
            overlapped_label_area=overlapped_label_area # TODO: Should be in label feature extraction
        )
        return image_quality_features
    
    def extract_features(self, images_folder_path):
        allowed_extensions = ['jpg', 'jpeg', 'png']
        image_files = []
        for image_file in os.listdir(images_folder_path):
            if image_file.rsplit('.', 1)[-1].lower() in allowed_extensions:
                image_files.append(os.path.join(images_folder_path, image_file))
        label_features = self.extract_label_features(images_folder_path)
        for i in range(len(image_files)):
            image_file = image_files[i]
            ocr_features = self.extract_ocr_based_features(image_file)
            visual_features = self.extract_visual_features(image_file)
            image_quality_features = self.extract_image_quality_features(image_file, label_features=label_features)
            self.features[image_file.split("/")[-1]] = {**ocr_features, **visual_features, **image_quality_features, **label_features.get(image_file.split("/")[-1], {})}

        features_df = pd.DataFrame.from_dict(self.features, orient='index')
        self.normalized_features = self._fit(features_df)
        self.normalized_features.to_csv("../../data/sample_images_ood/extracted_features_ood.csv", index=True)

        return self.normalized_features
            
    def _fit(self, features):
        # method for normalizing the feature value ranges to 0-1 
        imputer = SimpleImputer(strategy='median')

        numeric_features = features.columns[features.dtypes != 'object']
        detected_languages = self.min_max_values['detected_lang'][0]
        if detected_languages:
            detected_languages_dict = {}
            i = 0
            for lang in detected_languages:
                detected_languages_dict[lang] = i
                i += 1
            features['detected_lang_encoded'] = 0
            for row in features.itertuples():
                lang = row.detected_lang
                if lang in detected_languages_dict:
                    features.at[row.Index, 'detected_lang_encoded'] = detected_languages_dict[lang]
        self.min_max_values['detected_lang_encoded'] = [0, len(detected_languages) - 1]
                
        numeric_features = features.columns[features.dtypes != 'object']

        features[numeric_features] = imputer.fit_transform(features[numeric_features])
        
        min_max_scaler = MinMaxScaler(feature_range=(0, 1))
        features_for_scaling = features[numeric_features].copy()
        if 'detected_lang_encoded' not in self.min_max_values:
            self.min_max_values['detected_lang_encoded'] = features['detected_lang_encoded']
        for col in numeric_features:
            min_max_scaler.fit(pd.DataFrame(self.min_max_values[col], columns=[col]))
            features[col] = features[col].clip(self.min_max_values[col][0], self.min_max_values[col][1])
            features_for_scaling[col] = min_max_scaler.transform(features[[col]])

        return features_for_scaling

    
    def _get_languages_from_ocr(self, ocr_data):
        langdetect.DetectorFactory.seed = 0
        languages = dict()
        for block in ocr_data['block_num'].unique():
            ocr_data_block = ocr_data[ocr_data['block_num'] == block].dropna(subset=['text', 'conf'])
            block_text = ' '.join(ocr_data_block['text'].tolist())
            block_confidence = ocr_data_block['conf'].mean()
            if len(block_text.strip()) < 25 or block_confidence < 50 or 'museum' in block_text.lower() or 'herbarium' in block_text.lower() or \
            'herb.' in block_text.lower() or 'collection' in block_text.lower():
                continue
            try:
                lang = langdetect.detect_langs(block_text)
                language = str(lang[0]).split(':')[0]
                confidence = float(str(lang[0]).split(':')[1])
                if language not in languages:
                    languages[language] = {'conf': confidence, 'char_count': len(block_text), 'count': 1}
                else:
                    languages[language]['conf'] += confidence
                    languages[language]['char_count'] += len(block_text)
                    languages[language]['count'] += 1
            except:
                continue
        if len(languages) == 0:
            return 'zz', 0.0
        else:
            lang_values = dict()
            for language in languages:
                lang_values[language] = (languages[language]['conf'] / languages[language]['count'] * languages[language]['char_count'])
            detected_lang = max(lang_values, key=lang_values.get)
            return detected_lang, lang_values[detected_lang]
        
    def _calculate_background_heterogeneity(self, gray_image):
        _, thresh = cv2.threshold(gray_image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        background = gray_image[thresh == 255]
        if len(background) == 0:
            return 0.0
        return np.std(background)

    def _check_for_overlaps(self, input_image_path, label_features=None):
        # Match YOLO-detected labels with visual detection to find overlaps
        # TODO: Check also for B101126624.handwritten_data.jpg
        input_image = cv2.imread(input_image_path)
        gray = cv2.cvtColor(cv2.imread(input_image_path), cv2.COLOR_BGR2GRAY)
        _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        contours_coords = []

        for cnt in contours:
            contour_shape = cv2.approxPolyDP(cnt, 3, True)
            cv2.drawContours(input_image, [contour_shape], -1, (0, 255, 0), 2)
            # From numpy.org/doc/2.2/reference/generated/numpy.ravel.html
            contours_coords.append(contour_shape.ravel().tolist()) # flatten to list of x1,y1,x2,y2,...
        id = input_image_path.rsplit("/", 1)[-1]

        label_images = []

        label_images = self.features[id]['label_coordinates'] if id in self.features and 'label_coordinates' in self.features[id] else []
        overlap_ratio = np.float64(0.0)
        if type(label_images) == str:
            label_images = eval(label_images)
        if len(label_images) == 0:
            return overlap_ratio
        for label_image_coords in label_images:
            x1, y1, x2, y2 = label_image_coords  # unpack coordinates
            max_loc = (x1, y1)
            top_left = max_loc
            h = y2 - y1
            w = x2 - x1
            bottom_right = (top_left[0] + w, top_left[1] + h)

            for cnt_coords in contours_coords:
                if top_left[0] <= min(cnt_coords[0::2]) and bottom_right[0] >= max(cnt_coords[0::2]) and \
                    top_left[1] <= min(cnt_coords[1::2]) and bottom_right[1] >= max(cnt_coords[1::2]):
                    continue # matched region completely contains contour
                if min(cnt_coords[0::2]) <= top_left[0] and max(cnt_coords[0::2]) >= bottom_right[0] and \
                    min(cnt_coords[1::2]) <= top_left[1] and max(cnt_coords[1::2]) >= bottom_right[1]:
                    continue # contour completely contains matched region
                for i in range(0, len(cnt_coords), 2):
                    x, y = cnt_coords[i], cnt_coords[i+1]
                    if top_left[0] <= x <= bottom_right[0] and top_left[1] <= y <= bottom_right[1]:
                        # calculate overlap area
                        area = (min(bottom_right[0], max(cnt_coords[0::2])) - max(top_left[0], min(cnt_coords[0::2]))) * \
                                (min(bottom_right[1], max(cnt_coords[1::2])) - max(top_left[1], min(cnt_coords[1::2])))
                        if area / (w * h) < 0.5:
                            overlap_ratio += area / (w * h)
                            break
        return overlap_ratio
    
    def _identify_labels_using_yolo(self, images_folder_path):
        # Weights from HESPI's institutional label detector
        from ultralytics.models.yolo.detect.predict import DetectionPredictor

        weight_url = 'http://github.com/rbturnbull/hespi/releases/download/v0.4.0/sheet-component.pt.gz'
        weights_path_compressed = 'sheet-component.pt.gz'
        weights_path = 'sheet-component.pt'
        if not os.path.exists(weights_path):
            
            urllib.request.urlretrieve(weight_url, weights_path_compressed)
            with gzip.open(weights_path_compressed, 'rb') as file_in:
                with open(weights_path, 'wb') as file_out:
                    file_out.write(file_in.read())
            os.remove(weights_path_compressed)
        model = YOLO(weights_path, verbose=False)
        model.to('cpu')

        os.makedirs('temp_labels', exist_ok=True) # should be created to provide bboxes to classifier

        if not model.predictor:
            model.predictor = DetectionPredictor()
            
        model.predictor.setup_model(model=model.model)
        
        results = model.predict(source=images_folder_path, show=False, save=False, imgsz=1280, stream=True, verbose=False)

        label_dict = dict()

        for res in results:
            image = res.path
            if image not in label_dict:
                label_dict[image] = []
            sheet_boxes = res.boxes if res and len(res) > 0 else []
            for box in sheet_boxes:
                if box.cls == 9: # institutional label class
                    x1, y1, x2, y2 = box.xyxy[0]
                    label_dict[image].append((int(x1), int(y1), int(x2), int(y2)))
            
        return label_dict

In [ ]:
# TODO: Move class to classes, move script to ood.ipynb
images_folder_path = "../../data/sample_images_ood/" # 17m43s for 20 images
feature_extractor = FeatureExtractor()
features = feature_extractor.extract_features(images_folder_path)

print(features)

Ultralytics 8.4.11  Python-3.9.4 torch-2.8.0+cpu CPU (12th Gen Intel Core(TM) i5-1235U)
Model summary (fused): 92 layers, 25,846,129 parameters, 0 gradients, 78.7 GFLOPs
                      mean_conf  min_conf  std_conf  words_count  char_count  \
AMD.124313.jpg         0.542349       0.0  0.777034     0.094118    0.083158
BM000500117.jpg        0.730487       0.0  0.640571     0.176471    0.157077
BM000521755.jpg        0.725895       0.0  0.597508     0.336471    0.267535
BM000625345.jpg        0.477016       0.0  0.682325     0.190588    0.101218
BM000637970.jpg        0.593130       0.0  0.698339     0.352941    0.313314
BM000644348.jpg        0.490387       0.0  0.675012     0.216471    0.157077
BR0000005690732.jpg    0.810482       0.0  0.571454     0.145882    0.112558
BR0000011479499.jpg    0.560481       0.0  0.759492     0.131765    0.091978
BR0000027577110V.jpg   0.741294       0.0  0.656930     0.098824    0.099958
E00024823.jpg          0.524256       0.0  0.669259     0.324706    0.218816
E00026748.jpg          0.806828       0.0  0.623313     0.200000    0.187736
E00771642.jpg          0.709796       0.0  0.745776     0.381176    0.275514
EIG.7313.jpg           0.736104       0.0  0.600502     0.134118    0.120958
ERE0000074.jpg         0.508043       0.0  0.644261     0.204706    0.182696
HA.H1613656.jpg        0.626770       0.0  0.710118     0.355294    0.247795
HA.H9500180.jpg        0.562283       0.0  0.747407     0.127059    0.104578
K000345684.jpg         0.893505       0.0  0.492409     0.762353    0.727425
P05115347.jpg          0.332705       0.0  0.538723     0.207059    0.125157
TU252564.jpg           0.517304       0.0  0.671674     0.037647    0.012180
TU262103.jpg           0.529103       0.0  0.670689     0.009412    0.006720

                      num_text_lines  num_text_blocks  low_conf_ratio  \
AMD.124313.jpg              0.206897             0.40        0.500000
BM000500117.jpg             0.413793             0.36        0.280000
BM000521755.jpg             0.586207             0.48        0.265734
BM000625345.jpg             0.517241             0.40        0.543210
BM000637970.jpg             0.637931             1.00        0.446667
BM000644348.jpg             0.620690             1.00        0.554348
BR0000005690732.jpg         0.293103             0.56        0.161290
BR0000011479499.jpg         0.275862             0.44        0.500000
BR0000027577110V.jpg        0.224138             0.40        0.261905
E00024823.jpg               0.793103             0.44        0.507246
E00026748.jpg               0.344828             0.48        0.200000
E00771642.jpg               0.672414             0.72        0.345679
EIG.7313.jpg                0.275862             0.48        0.315789
ERE0000074.jpg              0.327586             0.40        0.505747
HA.H1613656.jpg             0.431034             0.32        0.397351
HA.H9500180.jpg             0.224138             0.28        0.500000
K000345684.jpg              0.344828             0.32        0.098765
P05115347.jpg               0.413793             0.72        0.761364
TU252564.jpg                0.275862             0.04        0.500000
TU262103.jpg                0.017241             0.04        0.250000

                      text_density  handwriting_ocr  ...  noise_sigma  \
AMD.124313.jpg            0.371609              0.0  ...     0.115186
BM000500117.jpg           0.582255              0.0  ...     0.242898
BM000521755.jpg           0.385422              0.0  ...     0.221203
BM000625345.jpg           0.486833              1.0  ...     0.201966
BM000637970.jpg           0.445819              0.0  ...     0.255424
BM000644348.jpg           0.258546              1.0  ...     0.221203
BR0000005690732.jpg       0.424017              0.0  ...     0.093492
BR0000011479499.jpg       0.108539              0.0  ...     0.140237
BR0000027577110V.jpg      0.193755              0.0  ...     0.152763
E00024823.jpg             0.039446              1.0  ...     0.115186
E00026748.jpg             0.122020              0.0  ...     0.080966
E00771642.jpg             0.147652              0.0  ...     0.093492
EIG.7313.jpg              0.067135              0.0  ...     0.196152
ERE0000074.jpg            0.568294              1.0  ...     0.336390
HA.H1613656.jpg           0.745248              0.0  ...     0.277118
HA.H9500180.jpg           0.081763              0.0  ...     0.152763
K000345684.jpg            0.077701              0.0  ...     0.224560
P05115347.jpg             0.045040              1.0  ...     1.000000
TU252564.jpg              0.036292              1.0  ...     0.046746
TU262103.jpg              0.096009              0.0  ...     0.140237

                      background_uniformity  overlapped_label_area  \
AMD.124313.jpg                     0.032509                    0.0
BM000500117.jpg                    0.608353                    0.0
BM000521755.jpg                    0.189111                    0.0
BM000625345.jpg                    0.334867                    0.0
BM000637970.jpg                    0.231077                    0.0
BM000644348.jpg                    0.248538                    0.0
BR0000005690732.jpg                0.508580                    0.0
BR0000011479499.jpg                0.320279                    0.0
BR0000027577110V.jpg               0.296878                    0.0
E00024823.jpg                      0.758395                    0.0
E00026748.jpg                      0.376672                    0.0
E00771642.jpg                      0.476976                    0.0
EIG.7313.jpg                       0.454517                    0.0
ERE0000074.jpg                     0.332812                    0.0
HA.H1613656.jpg                    0.386910                    0.0
HA.H9500180.jpg                    0.708688                    0.0
K000345684.jpg                     0.391111                    0.0
P05115347.jpg                      0.742625                    0.0
TU252564.jpg                       0.230598                    0.0
TU262103.jpg                       0.389505                    0.0

                      number_of_labels  mean_label_width  mean_label_height  \
AMD.124313.jpg                0.333333          1.000000           0.838417
BM000500117.jpg               0.333333          0.577974           0.348722
BM000521755.jpg               0.666667          0.618502           0.281121
BM000625345.jpg               0.666667          0.344493           0.147156
BM000637970.jpg               0.666667          0.438767           0.220940
BM000644348.jpg               0.666667          0.368722           0.332646
BR0000005690732.jpg           0.333333          1.000000           1.000000
BR0000011479499.jpg           0.666667          1.000000           0.991756
BR0000027577110V.jpg          0.333333          1.000000           1.000000
E00024823.jpg                 0.333333          1.000000           0.868096
E00026748.jpg                 0.333333          1.000000           1.000000
E00771642.jpg                 0.666667          1.000000           0.900247
EIG.7313.jpg                  0.333333          1.000000           1.000000
ERE0000074.jpg                0.333333          0.472247           0.316570
HA.H1613656.jpg               0.666667          1.000000           0.962077
HA.H9500180.jpg               0.666667          1.000000           0.881698
K000345684.jpg                0.666667          1.000000           1.000000
P05115347.jpg                 1.000000          1.000000           0.647156
TU252564.jpg                  0.000000          0.000000           0.000000
TU262103.jpg                  0.333333          1.000000           1.000000

                      label_spread     areas  handwritten_flag  \
AMD.124313.jpg            0.000000  1.000000               0.0
BM000500117.jpg           0.000000  0.219198               0.0
BM000521755.jpg           0.270632  0.342929               0.0
BM000625345.jpg           1.000000  0.122059               0.0
BM000637970.jpg           0.451127  0.211452               0.0
BM000644348.jpg           0.654627  0.258134               0.0
BR0000005690732.jpg       0.000000  1.000000               0.0
BR0000011479499.jpg       1.000000  1.000000               0.0
BR0000027577110V.jpg      0.000000  1.000000               0.0
E00024823.jpg             0.000000  1.000000               0.0
E00026748.jpg             0.000000  1.000000               0.0
E00771642.jpg             1.000000  1.000000               0.0
EIG.7313.jpg              0.000000  1.000000               0.0
ERE0000074.jpg            0.000000  0.162588               0.0
HA.H1613656.jpg           1.000000  1.000000               0.0
HA.H9500180.jpg           1.000000  1.000000               0.0
K000345684.jpg            1.000000  1.000000               0.0
P05115347.jpg             0.929033  1.000000               0.0
TU252564.jpg              0.000000  0.000000               0.0
TU262103.jpg              0.000000  1.000000               0.0

                      detected_lang_encoded
AMD.124313.jpg                     0.038462
BM000500117.jpg                    0.076923
BM000521755.jpg                    0.076923
BM000625345.jpg                    0.076923
BM000637970.jpg                    0.076923
BM000644348.jpg                    0.038462
BR0000005690732.jpg                0.423077
BR0000011479499.jpg                0.192308
BR0000027577110V.jpg               0.423077
E00024823.jpg                      0.076923
E00026748.jpg                      0.076923
E00771642.jpg                      0.076923
EIG.7313.jpg                       0.076923
ERE0000074.jpg                     0.076923
HA.H1613656.jpg                    0.076923
HA.H9500180.jpg                    0.076923
K000345684.jpg                     0.076923
P05115347.jpg                      0.038462
TU252564.jpg                       0.038462
TU262103.jpg                       0.038462

[20 rows x 30 columns]

In [ ]:
feature_extractor.features

{'AMD.124313.jpg': {'mean_conf': np.float64(51.3866121),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(38.81650709804676),
  'words_count': 40,
  'char_count': np.int64(198),
  'num_text_lines': 12,
  'num_text_blocks': 10,
  'low_conf_ratio': np.float64(0.5),
  'text_density': 0.06542126031778071,
  'handwriting_ocr': 0.0,
  'detected_lang': 'zz',
  'detected_lang_conf': 0.0,
  'text_area': 1322339,
  'mean_orientation': np.float64(0.3561899440411875),
  'relative_label_centroid_x': 0.5026536312849162,
  'relative_label_centroid_y': 0.8537902940134608,
  'resolution': 20.21268,
  'laplacian': np.float64(65.06188106083074),
  'contrast': np.float64(35.42754396778725),
  'brightness': np.float64(232.46603335134182),
  'noise': np.float64(4.22932683840045),
  'noise_sigma': np.float64(0.22833015757664546),
  'background_uniformity': np.float64(5.281372805448846),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(2266, 4272, 3565, 5289)],
  'mean_label_width': 1299.0,
  'mean_label_height': 1017.0,
  'label_spread': np.float64(0.0),
  'areas': 1321083.0,
  'handwritten_flag': 0.0},
 'BM000500117.jpg': {'mean_conf': np.float64(69.21242605333333),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(31.999563034515152),
  'words_count': 75,
  'char_count': np.int64(374),
  'num_text_lines': 24,
  'num_text_blocks': 9,
  'low_conf_ratio': np.float64(0.28),
  'text_density': 0.10250520566649599,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 173.99937467113108,
  'text_area': 300289,
  'mean_orientation': np.float64(0.32740572769429716),
  'relative_label_centroid_x': 0.48933333333333334,
  'relative_label_centroid_y': 0.879416282642089,
  'resolution': 2.9295,
  'laplacian': np.float64(439.610539333247),
  'contrast': np.float64(53.172837045772596),
  'brightness': np.float64(194.90763065369518),
  'noise': np.float64(5.63621266427718),
  'noise_sigma': np.float64(0.48148919434986953),
  'background_uniformity': np.float64(19.18238886812876),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(404, 86, 1060, 509)],
  'mean_label_width': 656.0,
  'mean_label_height': 423.0,
  'label_spread': np.float64(0.0),
  'areas': 277488.0,
  'handwritten_flag': 0.0},
 'BM000521755.jpg': {'mean_conf': np.float64(68.77737492307692),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(29.848329122003452),
  'words_count': 143,
  'char_count': np.int64(637),
  'num_text_lines': 34,
  'num_text_blocks': 12,
  'low_conf_ratio': np.float64(0.26573426573426573),
  'text_density': 0.06785301614273577,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 444.2364506865444,
  'text_area': 239589,
  'mean_orientation': np.float64(0.2320356141448733),
  'relative_label_centroid_x': 0.4876666666666667,
  'relative_label_centroid_y': 0.8338997451146983,
  'resolution': 3.531,
  'laplacian': np.float64(464.084685073631),
  'contrast': np.float64(41.18448862599102),
  'brightness': np.float64(208.55232880203909),
  'noise': np.float64(3.664426508071368),
  'noise_sigma': np.float64(0.43848431408642663),
  'background_uniformity': np.float64(9.061799102151493),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(831, 1658, 1432, 2220), (666, 2234, 1469, 2354)],
  'mean_label_width': 702.0,
  'mean_label_height': 341.0,
  'label_spread': np.float64(329.7390066401001),
  'areas': 434122.0,
  'handwritten_flag': 0.0},
 'BM000625345.jpg': {'mean_conf': np.float64(45.19643027160494),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(34.08536860388527),
  'words_count': 81,
  'char_count': np.int64(241),
  'num_text_lines': 30,
  'num_text_blocks': 10,
  'low_conf_ratio': np.float64(0.5432098765432098),
  'text_density': 0.0857064128256513,
  'handwriting_ocr': 1.0,
  'detected_lang': 'en',
  'detected_lang_conf': 30.999846248295277,
  'text_area': 256605,
  'mean_orientation': np.float64(0.24784221032145268),
  'relative_label_centroid_x': 0.6066666666666667,
  'relative_label_centroid_y': 0.8183867735470942,
  'resolution': 2.994,
  'laplacian': np.float64(359.8216697785574),
  'contrast': np.float64(41.61695447846316),
  'brightness': np.float64(208.0318396793587),
  'noise': np.float64(6.769651302605211),
  'noise_sigma': np.float64(0.40034967863048154),
  'background_uniformity': np.float64(12.580378387891498),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(924, 1634, 1378, 1931), (1067, 0, 1395, 60)],
  'mean_label_width': 391.0,
  'mean_label_height': 178.5,
  'label_spread': np.float64(1286.9812061564846),
  'areas': 154518.0,
  'handwritten_flag': 0.0},
 'BM000637970.jpg': {'mean_conf': np.float64(56.198095893333324),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(34.88532540534486),
  'words_count': 150,
  'char_count': np.int64(746),
  'num_text_lines': 37,
  'num_text_blocks': 27,
  'low_conf_ratio': np.float64(0.44666666666666666),
  'text_density': 0.07848580917874397,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 243.99899423079154,
  'text_area': 259945,
  'mean_orientation': np.float64(0.30791089289657336),
  'relative_label_centroid_x': 0.522,
  'relative_label_centroid_y': 0.8240489130434783,
  'resolution': 3.312,
  'laplacian': np.float64(379.79429255776),
  'contrast': np.float64(42.41552946893959),
  'brightness': np.float64(192.49434571256037),
  'noise': np.float64(7.208311896135266),
  'noise_sigma': np.float64(0.5063180735464505),
  'background_uniformity': np.float64(10.074869036479683),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(218, 1087, 687, 1342), (216, 1811, 743, 2092)],
  'mean_label_width': 498.0,
  'mean_label_height': 268.0,
  'label_spread': np.float64(549.6537546492337),
  'areas': 267682.0,
  'handwritten_flag': 0.0},
 'BM000644348.jpg': {'mean_conf': np.float64(46.463360010869565),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(33.72001159059251),
  'words_count': 92,
  'char_count': np.int64(374),
  'num_text_lines': 36,
  'num_text_blocks': 26,
  'low_conf_ratio': np.float64(0.5543478260869565),
  'text_density': 0.04551670006680027,
  'handwriting_ocr': 1.0,
  'detected_lang': 'zz',
  'detected_lang_conf': 0.0,
  'text_area': 136277,
  'mean_orientation': np.float64(0.3321109264902555),
  'relative_label_centroid_x': 0.5056666666666667,
  'relative_label_centroid_y': 0.8148797595190381,
  'resolution': 2.994,
  'laplacian': np.float64(525.1099776159577),
  'contrast': np.float64(37.04071073814273),
  'brightness': np.float64(197.4716900467602),
  'noise': np.float64(6.2594642618570475),
  'noise_sigma': np.float64(0.4384843140864309),
  'background_uniformity': np.float64(10.496365174686586),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(138, 648, 482, 1125), (895, 1390, 1388, 1720)],
  'mean_label_width': 418.5,
  'mean_label_height': 403.5,
  'label_spread': np.float64(797.5995627506325),
  'areas': 326778.0,
  'handwritten_flag': 0.0},
 'BR0000005690732.jpg': {'mean_conf': np.float64(76.7917716935484),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(28.546816712967217),
  'words_count': 62,
  'char_count': np.int64(268),
  'num_text_lines': 17,
  'num_text_blocks': 14,
  'low_conf_ratio': np.float64(0.16129032258064516),
  'text_density': 0.07464764926105014,
  'handwriting_ocr': 0.0,
  'detected_lang': 'nl',
  'detected_lang_conf': 108.99952152893108,
  'text_area': 4376629,
  'mean_orientation': np.float64(0.32486969279007744),
  'relative_label_centroid_x': 0.49405940594059405,
  'relative_label_centroid_y': 0.8753488372093023,
  'resolution': 58.6305,
  'laplacian': np.float64(113.23346923527617),
  'contrast': np.float64(61.33082328264036),
  'brightness': np.float64(173.4245721254296),
  'noise': np.float64(13.594358840535216),
  'noise_sigma': np.float64(0.1853252773132028),
  'background_uniformity': np.float64(16.773837782239674),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(16, 7306, 2736, 9660)],
  'mean_label_width': 2720.0,
  'mean_label_height': 2354.0,
  'label_spread': np.float64(0.0),
  'areas': 6402880.0,
  'handwritten_flag': 0.0},
 'BR0000011479499.jpg': {'mean_conf': np.float64(53.10459383928571),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(37.94022595890163),
  'words_count': 56,
  'char_count': np.int64(219),
  'num_text_lines': 16,
  'num_text_blocks': 11,
  'low_conf_ratio': np.float64(0.5),
  'text_density': 0.01910820787121691,
  'handwriting_ocr': 0.0,
  'detected_lang': 'fr',
  'detected_lang_conf': 36.99990403281458,
  'text_area': 670893,
  'mean_orientation': np.float64(0.3387482422751319),
  'relative_label_centroid_x': 0.6258691206543967,
  'relative_label_centroid_y': 0.8330779944289693,
  'resolution': 35.1102,
  'laplacian': np.float64(84.23420616728365),
  'contrast': np.float64(36.60549036121543),
  'brightness': np.float64(215.69848454295334),
  'noise': np.float64(8.234535434147341),
  'noise_sigma': np.float64(0.2779879159697976),
  'background_uniformity': np.float64(12.228219149595231),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(2780, 6004, 4475, 7173), (1693, 691, 3448, 1928)],
  'mean_label_width': 1725.0,
  'mean_label_height': 1203.0,
  'label_spread': np.float64(4047.6462450416784),
  'areas': 4152390.0,
  'handwritten_flag': 0.0},
 'BR0000027577110V.jpg': {'mean_conf': np.float64(70.23634742857142),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(32.81676302473466),
  'words_count': 42,
  'char_count': np.int64(238),
  'num_text_lines': 13,
  'num_text_blocks': 10,
  'low_conf_ratio': np.float64(0.2619047619047619),
  'text_density': 0.034110338031612085,
  'handwriting_ocr': 0.0,
  'detected_lang': 'nl',
  'detected_lang_conf': 110.99954698668222,
  'text_area': 1169300,
  'mean_orientation': np.float64(0.35230601222827285),
  'relative_label_centroid_x': 0.504517453798768,
  'relative_label_centroid_y': 0.8601363830089501,
  'resolution': 34.27993,
  'laplacian': np.float64(135.06756219581507),
  'contrast': np.float64(59.67026921665497),
  'brightness': np.float64(197.1051929802657),
  'noise': np.float64(14.093198440020151),
  'noise_sigma': np.float64(0.3028167951663689),
  'background_uniformity': np.float64(11.663303706175576),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(181, 5060, 1688, 6894)],
  'mean_label_width': 1507.0,
  'mean_label_height': 1834.0,
  'label_spread': np.float64(0.0),
  'areas': 2763838.0,
  'handwritten_flag': 0.0},
 'E00024823.jpg': {'mean_conf': np.float64(49.67233472463768),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(33.432657036062835),
  'words_count': 138,
  'char_count': np.int64(521),
  'num_text_lines': 46,
  'num_text_blocks': 11,
  'low_conf_ratio': np.float64(0.5072463768115942),
  'text_density': 0.006944488300529683,
  'handwriting_ocr': 1.0,
  'detected_lang': 'en',
  'detected_lang_conf': 157.9994936587104,
  'text_area': 428857,
  'mean_orientation': np.float64(0.1151749244951473),
  'relative_label_centroid_x': 0.6659486197542684,
  'relative_label_centroid_y': 0.6741932210269941,
  'resolution': 61.755018,
  'laplacian': np.float64(32.157193037035164),
  'contrast': np.float64(55.37581476386191),
  'brightness': np.float64(215.40890607464482),
  'noise': np.float64(8.040066217776829),
  'noise_sigma': np.float64(0.22833015757665776),
  'background_uniformity': np.float64(22.80442146255637),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(1723, 4844, 3169, 5897)],
  'mean_label_width': 1446.0,
  'mean_label_height': 1053.0,
  'label_spread': np.float64(0.0),
  'areas': 1522638.0,
  'handwritten_flag': 0.0},
 'E00026748.jpg': {'mean_conf': np.float64(76.44560025882353),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(31.137441483369553),
  'words_count': 85,
  'char_count': np.int64(447),
  'num_text_lines': 20,
  'num_text_blocks': 12,
  'low_conf_ratio': np.float64(0.2),
  'text_density': 0.02148152667989029,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 166.9993457127523,
  'text_area': 973779,
  'mean_orientation': np.float64(0.4171175493307655),
  'relative_label_centroid_x': 0.44940161914818727,
  'relative_label_centroid_y': 0.8641890198044623,
  'resolution': 45.330996,
  'laplacian': np.float64(603.8561244233694),
  'contrast': np.float64(66.6768106134118),
  'brightness': np.float64(190.3118951765366),
  'noise': np.float64(14.345356056151953),
  'noise_sigma': np.float64(0.16049639811664052),
  'background_uniformity': np.float64(13.589551801294686),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(2716, 5980, 5053, 7956)],
  'mean_label_width': 2337.0,
  'mean_label_height': 1976.0,
  'label_spread': np.float64(0.0),
  'areas': 4617912.0,
  'handwritten_flag': 0.0},
 'E00771642.jpg': {'mean_conf': np.float64(67.2519728148148),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(37.25501018551545),
  'words_count': 162,
  'char_count': np.int64(656),
  'num_text_lines': 39,
  'num_text_blocks': 18,
  'low_conf_ratio': np.float64(0.345679012345679),
  'text_density': 0.025994000333382835,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 580.9978481844154,
  'text_area': 1188893,
  'mean_orientation': np.float64(0.34257049668939726),
  'relative_label_centroid_x': 0.45780479210711766,
  'relative_label_centroid_y': 0.8917225117895259,
  'resolution': 45.737208,
  'laplacian': np.float64(293.6170077344995),
  'contrast': np.float64(62.92028998330278),
  'brightness': np.float64(195.43537653194747),
  'noise': np.float64(10.360984627658077),
  'noise_sigma': np.float64(0.18532527731320003),
  'background_uniformity': np.float64(16.0109113135074),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(3252, 6407, 5102, 8058), (20, 0, 1134, 533)],
  'mean_label_width': 1482.0,
  'mean_label_height': 1092.0,
  'label_spread': np.float64(5714.573174131206),
  'areas': 3648112.0,
  'handwritten_flag': 0.0},
 'EIG.7313.jpg': {'mean_conf': np.float64(69.74463380701754),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(29.99793152393903),
  'words_count': 57,
  'char_count': np.int64(288),
  'num_text_lines': 16,
  'num_text_blocks': 12,
  'low_conf_ratio': np.float64(0.3157894736842105),
  'text_density': 0.011819044104644932,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 95.78554743005263,
  'text_area': 560377,
  'mean_orientation': np.float64(0.3848908223901672),
  'relative_label_centroid_x': 0.5329569981736676,
  'relative_label_centroid_y': 0.8786204268292683,
  'resolution': 47.413056,
  'laplacian': np.float64(55.546167932881716),
  'contrast': np.float64(56.71554991800047),
  'brightness': np.float64(102.91352710949491),
  'noise': np.float64(13.063944348999566),
  'noise_sigma': np.float64(0.38882655569328295),
  'background_uniformity': np.float64(15.468740042132998),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(3293, 6319, 5609, 7822)],
  'mean_label_width': 2316.0,
  'mean_label_height': 1503.0,
  'label_spread': np.float64(0.0),
  'areas': 3480948.0,
  'handwritten_flag': 0.0},
 'ERE0000074.jpg': {'mean_conf': np.float64(48.13624866666666),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(32.18387645462691),
  'words_count': 87,
  'char_count': np.int64(435),
  'num_text_lines': 19,
  'num_text_blocks': 10,
  'low_conf_ratio': np.float64(0.5057471264367817),
  'text_density': 0.10004741784037559,
  'handwriting_ocr': 1.0,
  'detected_lang': 'en',
  'detected_lang_conf': 192.99899650915137,
  'text_area': 213101,
  'mean_orientation': np.float64(0.21990125539355154),
  'relative_label_centroid_x': 0.5,
  'relative_label_centroid_y': 0.8433802816901409,
  'resolution': 2.13,
  'laplacian': np.float64(2103.034504196532),
  'contrast': np.float64(45.04667745224643),
  'brightness': np.float64(208.08197558685447),
  'noise': np.float64(7.025269014084507),
  'noise_sigma': np.float64(0.6668144716630708),
  'background_uniformity': np.float64(12.53076146188761),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 1,
  'label_coordinates': [(653, 1340, 1189, 1724)],
  'mean_label_width': 536.0,
  'mean_label_height': 384.0,
  'label_spread': np.float64(0.0),
  'areas': 205824.0,
  'handwritten_flag': 0.0},
 'HA.H1613656.jpg': {'mean_conf': np.float64(59.38542892715231),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(35.47373987218985),
  'words_count': 151,
  'char_count': np.int64(590),
  'num_text_lines': 25,
  'num_text_blocks': 8,
  'low_conf_ratio': np.float64(0.3973509933774834),
  'text_density': 0.13120006549469593,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 435.99850890297273,
  'text_area': 8830179,
  'mean_orientation': np.float64(0.42903700569334274),
  'relative_label_centroid_x': 0.5094699862532458,
  'relative_label_centroid_y': 0.8296206225680934,
  'resolution': 67.30316,
  'laplacian': np.float64(118.89016878283164),
  'contrast': np.float64(48.57811110085926),
  'brightness': np.float64(178.26509450670667),
  'noise': np.float64(18.20979482984157),
  'noise_sigma': np.float64(0.5493229538099172),
  'background_uniformity': np.float64(13.836693881050754),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(4321, 8758, 6530, 10074), (1465, 9052, 2721, 10070)],
  'mean_label_width': 1732.5,
  'mean_label_height': 1167.0,
  'label_spread': np.float64(2384.723477156209),
  'areas': 4185652.0,
  'handwritten_flag': 0.0},
 'HA.H9500180.jpg': {'mean_conf': np.float64(53.2754170925926),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(37.33650500329714),
  'words_count': 54,
  'char_count': np.int64(249),
  'num_text_lines': 13,
  'num_text_blocks': 7,
  'low_conf_ratio': np.float64(0.5),
  'text_density': 0.014394292787663389,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 68.99953900965893,
  'text_area': 400836,
  'mean_orientation': np.float64(0.3853279470786757),
  'relative_label_centroid_x': 0.26669248644461657,
  'relative_label_centroid_y': 0.7420027816411683,
  'resolution': 27.84687,
  'laplacian': np.float64(67.84088691990941),
  'contrast': np.float64(59.009326542258485),
  'brightness': np.float64(203.31762309372652),
  'noise': np.float64(7.9499499943799785),
  'noise_sigma': np.float64(0.3028167951663922),
  'background_uniformity': np.float64(21.604494770692803),
  'overlapped_label_area': np.float64(0.0),
  'number_of_labels': 2,
  'label_coordinates': [(395, 494, 2870, 1847), (2223, 2397, 3719, 3183)],
  'mean_label_width': 1985.5,
  'mean_label_height': 1069.5,
  'label_spread': np.float64(1709.0784980509234),
  'areas': 4524531.0,
  'handwritten_flag': 0.0},
 'K000345684.jpg': {'mean_conf': np.float64(84.65809625925925),
  'min_conf': np.float64(0.0),
  'std_conf': np.float64(24.598129790660803),
  'words_count': 324,
  'char_count': np.int64(1732),
  'num_text_lines': 20,
  'num_text_blocks': 8,
  'low_conf_ratio': np.float64(0.09876543209876543),
  'text_density': 0.013679190497089813,
  'handwriting_ocr': 0.0,
  'detected_lang': 'en',
  'detected_lang_conf': 1606.280684161071,
  'text_area': 952805,
  'mean_orientation': np.float64(0.4535489865946729),
  'relative_label_centroid_x': 0.481981981981982,
  'relative_label_centroid_y': 0.830070437124508,
  'resolution': 69.65361,
  'laplacian': np.float64(92.55040882591305),
  'contrast': np.float64(50.74593380871588),
  'brightness': np.float64(183.34638411419022),
  'noise': np.float64(12.52460173995289),

In [ ]:
# Extract bounding box coordinates for each image.
bounding_boxes = dict()
# from column label_coordinates
for key, value in feature_extractor.features.items():
    if 'label_coordinates' in value and value['label_coordinates']:
        label_coordinates = value['label_coordinates']
        print(label_coordinates)
        if type(label_coordinates) == str:
            label_coordinates = eval(label_coordinates)
        if len(label_coordinates) > 0:
            x_min = min([box[0] for box in label_coordinates])
            y_min = min([box[1] for box in label_coordinates])
            x_max = max([box[2] for box in label_coordinates])
            y_max = max([box[3] for box in label_coordinates])
            bounding_boxes[key.rsplit('.', 1)[0]] = (x_min, y_min, x_max, y_max)
bounding_boxes_df = pd.DataFrame.from_dict(bounding_boxes, orient='index', columns=['x_min', 'y_min', 'x_max', 'y_max'])
bounding_boxes_df.to_csv("../../data/sample_images_ood/bounding_boxes_ood.csv", index=True)

[(2266, 4272, 3565, 5289)]
[(404, 86, 1060, 509)]
[(831, 1658, 1432, 2220), (666, 2234, 1469, 2354)]
[(924, 1634, 1378, 1931), (1067, 0, 1395, 60)]
[(218, 1087, 687, 1342), (216, 1811, 743, 2092)]
[(138, 648, 482, 1125), (895, 1390, 1388, 1720)]
[(16, 7306, 2736, 9660)]
[(2780, 6004, 4475, 7173), (1693, 691, 3448, 1928)]
[(181, 5060, 1688, 6894)]
[(1723, 4844, 3169, 5897)]
[(2716, 5980, 5053, 7956)]
[(3252, 6407, 5102, 8058), (20, 0, 1134, 533)]
[(3293, 6319, 5609, 7822)]
[(653, 1340, 1189, 1724)]
[(4321, 8758, 6530, 10074), (1465, 9052, 2721, 10070)]
[(395, 494, 2870, 1847), (2223, 2397, 3719, 3183)]
[(2497, 8495, 4872, 9653), (2302, 5, 7144, 3501)]
[(751, 56, 2056, 849), (2066, 21, 3301, 1037), (2196, 1040, 3292, 1586)]
[(3288, 7402, 6375, 9430)]

In [ ]:
# label_features, extracted_features = feature_extraction('../../data/sample_images_ood/')
label_features, extracted_features = feature_extractor.extract_features('../../data/sample_images_stratified_after_filter/') # 206m57s for 1838 images
extracted_features

Ultralytics 8.4.11  Python-3.9.4 torch-2.8.0+cpu CPU (12th Gen Intel Core(TM) i5-1235U)
Model summary (fused): 92 layers, 25,846,129 parameters, 0 gradients, 78.7 GFLOPs

image 1/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100000390.jpg: 1280x832 2 handwritten datas, 4 stamps, 6 annotation labels, 1 scale, 1 swatch, 1 number, 851.1ms
image 2/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100001491.jpg: 1280x800 4 handwritten datas, 3 stamps, 1 scale, 1 institutional label, 2 numbers, 772.6ms
image 3/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100001493.jpg: 1280x800 4 stamps, 1 scale, 2 institutional labels, 2 numbers, 770.0ms
image 4/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100001916.jpg: 1280x800 3 stamps, 1 scale, 1 institutional label, 2 numbers, 808.5ms
image 5/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100002521.jpg: 1280x800 2 stamps, 1 scale, 2 institutional labels, 2 numbers, 801.3ms
image 6/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100002801.jpg: 1280x832 3 handwritten datas, 2 stamps, 1 annotation label, 1 scale, 2 swatchs, 2 institutional labels, 2 numbers, 826.1ms
image 7/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100002884.jpg: 1280x832 4 stamps, 1 annotation label, 1 scale, 1 institutional label, 2 numbers, 843.4ms
image 8/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100003200.jpg: 1280x832 1 handwritten data, 4 stamps, 3 annotation labels, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1469.5ms
image 9/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100003483.jpg: 1280x832 2 stamps, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1568.1ms
image 10/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100005500.jpg: 1280x832 2 handwritten datas, 3 stamps, 1 scale, 1 institutional label, 2 numbers, 1494.6ms
image 11/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100005618.jpg: 1280x832 3 stamps, 1 scale, 1 institutional label, 2 numbers, 1463.4ms
image 12/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100007999.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1676.9ms
image 13/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100008325.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1933.3ms
image 14/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100008830.jpg: 1280x896 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1847.3ms
image 15/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100010571.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 2038.0ms
image 16/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100010881.jpg: 1280x896 2 stamps, 1 scale, 1 swatch, 1 institutional label, 1 number, 1801.7ms
image 17/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100010886.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1915.4ms
image 18/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100012080.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1878.6ms
image 19/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100012130.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1760.1ms
image 20/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100012133.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1739.4ms
image 21/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013001.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1695.7ms
image 22/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013019.jpg: 1280x896 1 stamp, 1 swatch, 1 institutional label, 1 number, 1712.1ms
image 23/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013077.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1725.4ms
image 24/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013079.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1757.1ms
image 25/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013113.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1910.1ms
image 26/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013143.jpg: 1280x896 1 stamp, 1 annotation label, 1 scale, 1 swatch, 2 institutional labels, 1 number, 1981.7ms
image 27/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013533.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 2042.9ms
image 28/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013541.jpg: 1280x896 1 handwritten data, 2 scales, 1 swatch, 1 institutional label, 1 number, 1855.5ms
image 29/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013542.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1760.4ms
image 30/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100013596.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1759.2ms
image 31/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100015025.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1790.1ms
image 32/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100020286.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1842.4ms
image 33/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100023819.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1762.7ms
image 34/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100025085.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1759.0ms
image 35/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100025104.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1686.3ms
image 36/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100027055.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1874.3ms
image 37/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100029096.jpg: 1280x896 1 stamp, 1 swatch, 1 institutional label, 1 number, 1779.6ms
image 38/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100029925.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1805.9ms
image 39/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100030148.jpg: 1280x832 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1612.5ms
image 40/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100030420.jpg: 1280x928 1 stamp, 1 scale, 3 swatchs, 1 institutional label, 1 number, 1917.1ms
image 41/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100030508.jpg: 1280x832 2 stamps, 1 annotation label, 1 scale, 1 swatch, 1 institutional label, 1 number, 1727.9ms
image 42/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100043258.jpg: 1280x896 3 stamps, 1 scale, 1 swatch, 1 institutional label, 1 number, 1695.3ms
image 43/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100043259.jpg: 1280x896 3 stamps, 1 scale, 1 swatch, 1 institutional label, 1 number, 1772.6ms
image 44/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100046494.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1752.3ms
image 45/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100046516.jpg: 1280x896 1 handwritten data, 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1678.2ms
image 46/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100046524.jpg: 1280x896 1 stamp, 2 scales, 1 swing tag, 1 swatch, 1 institutional label, 2 numbers, 1807.3ms
image 47/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100046535.jpg: 1280x896 1 stamp, 2 scales, 1 swatch, 1 institutional label, 1 number, 1751.1ms
image 48/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100046795.jpg: 1280x896 1 stamp, 1 swatch, 1 institutional label, 1 number, 1748.1ms
image 49/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100046958.jpg: 1280x896 1 stamp, 1 swatch, 1 institutional label, 1 number, 1749.0ms
image 50/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100047225.jpg: 1280x896 1 stamp, 1 annotation label, 1 scale, 3 swing tags, 1 swatch, 1 institutional label, 1 number, 1802.4ms
image 51/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100047902.jpg: 1280x896 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1676.8ms
image 52/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100048005.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1854.8ms
image 53/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100048052.jpg: 1280x896 1 handwritten data, 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1833.5ms
image 54/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100048267.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1913.3ms
image 55/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100048981.jpg: 1280x832 2 stamps, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1689.2ms
image 56/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100049843.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 2433.5ms
image 57/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100050741.jpg: 1280x896 1 stamp, 1 swatch, 1 institutional label, 1 number, 1948.7ms
image 58/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100051118.jpg: 1280x896 1 stamp, 2 scales, 1 swatch, 1 institutional label, 1 number, 1723.3ms
image 59/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100051145.jpg: 1280x896 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1749.2ms
image 60/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100051153.jpg: 1280x896 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1670.8ms
image 61/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100051859.jpg: 1280x896 1 stamp, 2 scales, 1 swatch, 1 institutional label, 1 number, 1769.3ms
image 62/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100054944.jpg: 1280x832 1 scale, 1 swatch, 1 institutional label, 1 number, 1706.1ms
image 63/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100055545.jpg: 1280x832 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1648.2ms
image 64/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100058346.jpg: 1280x832 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1718.6ms
image 65/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100058356.jpg: 1280x832 2 stamps, 1 scale, 1 swatch, 1 institutional label, 1 number, 1705.1ms
image 66/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100066610.jpg: 1280x832 3 stamps, 1 annotation label, 1 scale, 1 institutional label, 3 numbers, 1730.3ms
image 67/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100067590.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1840.9ms
image 68/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100070040.jpg: 1280x832 1 handwritten data, 1 stamp, 1 scale, 1 institutional label, 2 numbers, 1687.4ms
image 69/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100086436.jpg: 1280x832 3 stamps, 1 scale, 1 swatch, 1 institutional label, 2 numbers, 1700.2ms
image 70/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100086706.jpg: 1280x832 2 stamps, 1 annotation label, 1 scale, 1 institutional label, 2 numbers, 1694.5ms
image 71/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100088818.jpg: 1280x896 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1706.6ms
image 72/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100089444.jpg: 1280x832 3 stamps, 1 scale, 1 institutional label, 2 numbers, 1645.4ms
image 73/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100089768.jpg: 1280x832 3 stamps, 1 scale, 1 institutional label, 2 numbers, 1715.0ms
image 74/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100094275.jpg: 1280x800 3 stamps, 1 scale, 2 institutional labels, 2 numbers, 1642.3ms
image 75/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100096136.jpg: 1280x832 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1566.6ms
image 76/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100097716.jpg: 1280x896 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 2 numbers, 1717.1ms
image 77/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100097847.jpg: 1280x832 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1603.6ms
image 78/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100097875.jpg: 1280x832 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1528.2ms
image 79/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100097892.jpg: 1280x832 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1562.7ms
image 80/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100097905.jpg: 1280x832 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1593.9ms
image 81/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100097906.jpg: 1280x832 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1556.4ms
image 82/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100103718.jpg: 1280x832 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1671.1ms
image 83/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100104150.jpg: 1280x832 1 stamp, 1 scale, 1 swatch, 1 institutional label, 1 number, 1672.7ms
image 84/1838 c:\Users\mernst\Nextcloud\Voucher classifier\master_thesis\notebooks\ocr\..\..\data\sample_images_stratified_after_filter\B100106420.jpg: 1280x832 1 stamp, 1 scale, 1 swing tag, 1 swatch, 1 institutional label, 1 number, 1823.0ms

C:\Users\mernst\AppData\Local\Temp\ipykernel_25784\898035321.py:147: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  features['detected_lang'].fillna('ZZ', inplace=True)

,mean_conf,min_conf,std_conf,words_count,char_count,num_text_lines,num_text_blocks,low_conf_ratio,text_density,handwriting_ocr,...,background_uniformity,overlapped_label_area,number_of_labels,label_coordinates,mean_label_width,mean_label_height,label_spread,areas,handwritten_flag,detected_lang_encoded
B100000390,0.423216,0.000000,0.628260,0.254118,0.162957,0.379310,0.56,0.694444,0.950025,1.0,...,0.507357,0.000000,0.000000,[],0.000000,0.000000,0.000000,0.000000,0.0,0.192308
B100001491,0.679137,0.145996,0.626008,0.049412,0.037799,0.155172,0.16,0.333333,0.408264,0.0,...,0.534504,0.000000,0.333333,"[(1, 1452, 410, 1699)]",0.360352,0.203627,0.000000,0.079802,0.0,1.000000
B100001493,0.586925,0.032075,0.653231,0.047059,0.037799,0.155172,0.20,0.550000,0.461537,0.0,...,0.438117,0.000216,0.666667,"[(0, 1442, 417, 1699), (557, 1288, 734, 1394)]",0.261674,0.149629,0.319428,0.099478,0.0,0.230769
B100001916,0.752303,0.307856,0.420270,0.063529,0.053759,0.258621,0.44,0.148148,0.237126,0.0,...,0.091892,0.000000,0.333333,"[(0, 1324, 458, 1677)]",0.403524,0.291014,0.000000,0.127712,0.0,1.000000
B100002521,0.782928,0.000000,0.571064,0.254118,0.209576,0.431034,0.48,0.203704,0.397334,0.0,...,0.501822,0.231876,0.666667,"[(10, 1512, 457, 1693), (7, 1174, 429, 1509)]",0.382819,0.212696,0.176598,0.175585,0.0,0.230769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B109006639,0.494663,0.510683,0.641531,0.002353,0.002940,0.017241,0.04,1.000000,0.350355,1.0,...,0.292418,0.000000,0.333333,"[(37, 2047, 752, 2430)]",0.629956,0.315746,0.000000,0.216320,0.0,1.000000
B109008122,0.584999,0.079985,0.612794,0.051765,0.038219,0.120690,0.16,0.409091,0.347018,0.0,...,0.234531,0.000000,0.333333,"[(32, 2045, 744, 2420)]",0.627313,0.309151,0.000000,0.210913,0.0,0.230769
B109008139,0.638427,0.000000,0.800212,0.040000,0.027299,0.103448,0.16,0.411765,0.372169,0.0,...,0.395106,0.000034,0.333333,"[(27, 2038, 652, 2424)]",0.550661,0.318219,0.000000,0.190572,0.0,1.000000
B109008945,0.490955,0.000000,0.611505,0.150588,0.114658,0.103448,0.04,0.515625,0.394775,1.0,...,0.390039,0.000000,0.333333,"[(27, 1869, 715, 2438)]",0.606167,0.469085,0.000000,0.309238,0.0,1.000000
B109008954,0.613293,0.000000,0.669017,0.044706,0.019740,0.068966,0.08,0.368421,0.035875,0.0,...,0.379434,0.003209,0.333333,"[(25, 2043, 642, 2429)]",0.543612,0.318219,0.000000,0.188133,0.0,0.538462

In [ ]:
extracted_features_export = extracted_features.drop(columns=['detected_lang', 'label_coordinates'])
extracted_features_export.to_csv('../../data/features/extracted_handcrafted_features_ood_minmax.csv', index=True)

In [ ]:
label_features.index = label_features.index.str.split('.').str[0]
label_features = label_features.drop(columns=['label_coordinates']) # drop label_coordinates for now
scaler = MinMaxScaler()
label_features_scaled = scaler.fit_transform(label_features)
label_features = pd.DataFrame(label_features_scaled, columns=label_features.columns, index=label_features.index)
label_features.to_csv('../../data/features/label_features_normalized_ood_minmax.csv')
label_features

,number_of_labels,mean_label_width,mean_label_height,label_spread,areas,handwritten_flag
B100000390,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
B100001491,0.333333,0.360352,0.203627,0.000000,0.079802,0.0
B100001493,0.666667,0.261674,0.149629,0.319428,0.099478,0.0
B100001916,0.333333,0.403524,0.291014,0.000000,0.127712,0.0
B100002521,0.666667,0.382819,0.212696,0.176598,0.175585,0.0
...,...,...,...,...,...,...
B109006639,0.333333,0.629956,0.315746,0.000000,0.216320,0.0
B109008122,0.333333,0.627313,0.309151,0.000000,0.210913,0.0
B109008139,0.333333,0.550661,0.318219,0.000000,0.190572,0.0
B109008945,0.333333,0.606167,0.469085,0.000000,0.309238,0.0
B109008954,0.333333,0.543612,0.318219,0.000000,0.188133,0.0

In [ ]:
input_images_folder = '../../data/sample_images_stratified_after_filter/'

features = feature_extractor.extract_features(input_images_folder)
features_df = pd.DataFrame.from_dict(features, orient='index')
features_df.to_csv('../../data/features/extracted_handcrafted_features_ood_minmax.csv', index_label='image_path')

NameError: name 'image_files' is not defined